####
# ATTENTION:
# Replace all occurrences of teste-convenia with your project's name.
####

# v3 syntax
version: '3'

# Named volumes
volumes:

  # MySQL Data
  teste-convenia-mysql-data:
    driver: local

  # Redis Data
  teste-convenia-redis-data:
    driver: local

services:

  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: teste-convenia-mysql
    volumes:
      - teste-convenia-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=teste-convenia
      - MYSQL_DATABASE=teste-convenia
      - MYSQL_USER=teste-convenia
      - MYSQL_PASSWORD=teste-convenia

  # Redis
  cache:
    image: redis:4.0
    container_name: teste-convenia-redis
    command: --appendonly yes
    volumes:
      - teste-convenia-redis-data:/data
    ports:
      - "6379:6379"

  # PHP (with Nginx)
  app:
    image: ambientum/php:7.3-nginx
    container_name: teste-convenia-app
    volumes:
      - .:/var/www/app
    ports:
      - "8080:8080"
    links:
      - mysql
      - cache

  # Laravel Queues
  queue:
    image: ambientum/php:7.3
    container_name: teste-convenia-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - mysql
      - cache
